language: node_js
node_js:
  - node
script: npm run build:prod
deploy:
  provider: firebase
  token:
    secure: "Bq6o+Z4lbuGydq3sRec74rJwQRGn4Vzi0S0TQX7sFUyqUv5fNGtecinGlkMmoft/5QUbX0ayFz4DkfKaU+Z8p7yQcwHyZJ0QD1mUBXdSa0ljbfbWnCjW0m4gu6pzh8Cr7x68Y6lSJIY3QaJEQlIYWO5V4iZZ0k6mpJhcLP60M9uRUHDc1ZFpYli86QnKgOFHALDXSqvgPUPAL52Mp+lotL7VsptU18/nbp5f+XeZ6xX0faDxqHFhbk7DaYh2LXAc5/+xjCJOuTkk+pEEgzvcHTW2L3okyo3lzceIPHouRmFRTtW8TXZ2UMgTqv8V4KvnJyIhiyoEnIOKKiV3ZGJDidqiCnl0Yk/CXQOtWOSlklV0gqSKzT892xmceGpBiDL8JiQntSjOPf5e+F1jT2NHE0DxglkY0petTCijUl2ZAsVcBajVeofPKm2Qe88BtY8jyUR2n/vMf1xFSVUAYx0/IPSSFseZkyfif3CyfTWMFMs3vh9c/imsKk/oIzg92PIP3tGrc9k+WNHEhCW4GiHA/STKFefYw9mmCqwhI6DYezfE3CPtiBl/5mN3S4GECud5NBT4VLAoA49Lx2IMcNdZbxy5aJj62P+xD+cnfdOf0Dz5KRzNHkKLRsSazwZYW/fqHgrmfL8NmbQxoUWJcZeiPatXyvLKJaglxxtA5/03lJU="

