language: node_js
node_js:
  - node
script: npm run build:prod
deploy:
  provider: firebase
  token:
    secure: WsUKPPGlYPAcMwJNyWB7hHtCyEpCvYMHyQqt8ZGH33R+UZIf8zb0efGNRKC4cv10b67Svl8+3e+JMdhVT/0Bv4CutyKwXgO/n69tfKMO0qSjzQoQ7jSPJ2WHobzizn2V8X55BdxkyKgLaVVhMw8amcgF/uvJ4mbC+zK1f37F3K6iCUWNTaHsTk4XyM0n5hlm+OhgKaJt8KflH2tJJ4E7GAtMVRxvmBxD71YckbEHqGj4ECK76mgEXa4jnxi8YhMX1NmcGjBfyeruK01/xT0XRajfu7ifwbcKMexPgy4l66SRTS0YttzyZ5VldwiIAIR9OEFdPYl1A0QOhHx3Ru7iBi0Xbk/gX4jxs7BavDfdkGyIzuSl7H9fzQrH9ROz0G6L97HjmoWYacoJDECLX9fMUS1/NqNbmh8SLBC69iJ1q0Fyi+GUNKkUsxKmkMOFoRzACihaU52aM9egbGrWtKOUbRJ1AYjCT356C+UdMJ0ONWW5f5ZPrHs1XWuF3jx28FC1IIWluRsjEhIEtq5DOBlUK0UW5P2IDq6vhuJa1W0zaRXiVGe/FrK0cRSLwpMfhdp6P2/ivuPSuahv2b9+m8gOqTGOjLNNW4UzMlKdrGJxfhKxg4Bz9J+Cs6HArbkhVLZZ9KAFaAqiUxYJybh4+YoaWFKAS08HmsSNl/4uEF+js0c=
