language: node_js
node_js:
  - node
script: npm run build:prod
before_deploy:
- npm install -g firebase-tools
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: "yVV5eaibW8gf6xv7SCmYnD4b+FwcYxQTz6FrPeocCHzxhQF/YbSyGFzH4gKJ6DA2djEtZTMIiuZZr2F8JPftOVNWrRxsNRCMY54zcwtB6MPmc0u/sHi0ySjPtxoOdBZY0GSalONgTlSjlkEYnNABpCSM4e2L8/c2H8GKAdjJLLcfMLK+Ruefrwf5yJ+0cStJgQJ3/TAO4RRwavSktANrcYihC6hg2lIyXLmT05v64tthAOAAgZpCWfuIiux3W2eiZRxxpNGBq/lspmC+rBhcf6L/m+w4RoOb6OhE/Ny86lFJ+Zcl9i+oC9xzLuJljevlbdpKFkNsjrSeeSnTh1OV7s9EFizqP78XBjN93zwzsiWfTe4dc5s7e2kw1dbRrYVcENlJLAJ0XoRbuUsTA5tXYk1XTwDKAiJnmDojBwEfh4vgFfYXO3/26zE3JgRaqG52Ass8HnmYXlYdxGDm0f9eeYcNSFneVoX5FYn3qeQvkzL3IdOkY9K6VVb1J3hYp1DXiyHTPm/tiGhrS8Tx93zWlPwuHldNu+HkfzQrG0BuX6RL2MyfRSREzfrJN30Jmm27myPuPRAPjZd3IthzUxmKhBJbyJZutnUInQO0TVhoQ3SqkWxKqxb7VnF5BBC6gOUyRX2wPXdmmQYSH9MB5sIr0Sw7vIIYcJojWExVIKERwhY="
  project: fifa
